site_name: The Colorful Creature
theme:
  name: material
  palette:
    - scheme: slate
      primary: red
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: red
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - language.selector

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true

extra:
  alternate:
    - name: English
      link: ../
      lang: en
      progress: 100%

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en: English

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Game:
      - Overview: game.md
  - Engine: engine.md